### ISSUE TITLE
해당 플러그인은 GPLv3라이선스를 위반하고 있습니다

### ISSUE THREAD

**Issue by PresentKim** [Flug-in-Fabrik/Pmarket#1]
아래와 같이 현재 Pmarket 플러그인은 onebone님의 [**EconomyS**](https://github.com/onebone/EconomyS) 중 **EconomyAPI**를 경제 시스템 API로 채택해 사용하고 계십니다. https://github.com/Flug-in-Fabrik/Pmarket/blob/ee57c3b115a68037ce3ab87b52362c2e1904ce13/%EC%83%81%EC%A0%90/src/Pmarket/Main.php#L42

**EconomyS**의 경우 GPLv3 라이선스로 보호받고 있습니다. [LICENSE](https://github.com/onebone/EconomyS/blob/3.x/LICENSE)
위 라이선스에 명시된 대로 해당 저작물의 소스코드를 이용하는 경우 파생물 라이선스 전염성에 의해 GPLv3라이선스가 적용되며 이를 무단으로 수정할 수 없습니다.

따라서 해당 플러그인에 적용된 라이선스는 `Fabrik-EULA`가 아닌 `GPLv3`여야합니다.

**Comment by JellyBrick** [comment]
혹은 `GPLv3`와 호환되는 라이센스여야 합니다.

예: `AGPLv3`

**Comment by PresentKim** [comment]
그냥 Close 하고 도주하겠습니다!
